### PR TITLE
Add full stop at end of intro paragraph

### PR DESCRIPTION
**Pull request by JohnVeness**

### CODE REVIEW

**Comment by JohnVeness** [comment]
Thanks for merging this.

It doesn't seem to be affecting release notes on the site though, e.g. for 115.6.1 which was new since this merge. Have I edited the wrong file? Should I edit https://github.com/thunderbird/thunderbird-website/blob/master/website/includes/_enonly/release-notes.html instead?

**Comment by jfx2006** [comment]
> Thanks for merging this.
> 
> It doesn't seem to be affecting release notes on the site though, e.g. for 115.6.1 which was new since this merge. Have I edited the wrong file? Should I edit https://github.com/thunderbird/thunderbird-website/blob/master/website/includes/_enonly/release-notes.html instead?

Oh... yeah I always forget that those templates are duplicated like that. 

https://github.com/thunderbird/thunderbird-website/pull/550

**Comment by JohnVeness** [comment]
Thanks. Maybe there should be a note about this in the README, and/or as a comment in the file itself?

**Comment by Sancus** [comment]
[We'll change this when we do the redesign](https://github.com/thunderbird/thunderbird-notes/issues/24), likely by removing the template from this repository and making the website repo's template the canonical one.

**Pull request merged**
